### PR TITLE
Change height and width of grid as screen size changes to keep app all on one screen in mobile view

### PR DESCRIPTION
**Pull request by lauriebatchelor**

### CODE REVIEW

**Comment by teleshoes** [comment]
woo! this works great on my mobile, thanks!

i think the max is way too small, tho. the words are tiny on my laptop and 1600p tablet.

IMO, you can just drop the maximum.
```
const height = window.innerHeight - 275
const width = (height * 5) / 6
```

theres no reason not to make the letters take up literally all the room the keyboard doesnt, unless we make the keyboard grow too. (havent looked, but maybe just `width: 66%/34%` would work better)

**Comment by lauriebatchelor** [comment]
@teleshoes Here is a screenshot of what it looks like on my 15" 1080p laptop vs what wordle looks like on the same laptop.  I'm guessing the grid looks much smaller on your laptop and tablet?  Would you be able to send a screenshot? What does wordle look like on these devices for you as well?

image

image

Without either the max height or width it looks like this in developer tools on the Galaxy phones and newer iPhones.  

image

image

We could change it to 

```
const height = innerh - 275
const width = Math.min(333, (height * 5) / 6)
```

which makes the grid always fill up the available height but makes the tiles oval shaped on newer devices.  Would be good to know what both wordle and this look like on these devices in person

**Comment by teleshoes** [comment]
ah, i see. what do you think of this approach instead?
- calculate the grid height+width
- remove margins, split into cells, calculate the max letter height and max letter width
- set both height and width to min(height, width)
  - could do width=min(height*0.8, width) for tall rectangles/ovals instead of squares/circles
- repeat for keyboard
- use the targets to set the cell sizes and let the grid/kb flow
- use the targets to calculate the font size

https://github.com/teleshoes/word-master/compare/75ea8b6c4ce7fda0a541f1075d9f9560e6c7f726...teleshoes:resize_fonts

it seems to work well on my devices, allows both parts to get very large but never cut off.
if you like the idea or any part of it, feel free to use it here (or not of course).

**Comment by lauriebatchelor** [comment]
@teleshoes This looks great.  The keyboard is too small for me on my mobile (iPhone 6s) though.  I deployed on firebase to see what it would be like: https://fir-word-master.web.app/.  How is it on your phone?

Closed this pr as committed on main instead of a new branch.  Will create issue as contributing guide recommends and mention both versions as possible solutions

**Comment by teleshoes** [comment]
that link looks great on my 4" (720p) phone, 15" (1080p) laptop, 14" (1440p) laptop, and 65" (1080p) TV

yea, keyboard is maybe a bit small on my tiny mobile. perhaps 67/34 => 60/40?
or we could calculate heightKB=Math.max(height/3, 250) and heightGrid=height-heightKB.

anyway, hope your new PR gets merged, its a real nice improvement!

**Pull request closed without merging**
