### PR TITLE
Add share button that copies a wordle-style grid of emoji to the clipboard

### PR DESCRIPTION
**Pull request by cmot17**
Wordle puts the number of the puzzle in the output, but since Word Master is randomized I left that out, so here is an example output:

Word Master 5/6

⬛⬛⬛⬛⬛
⬛⬛⬛🟨🟩
⬛🟩⬛⬛🟩
⬛🟩⬛🟩🟩
🟩🟩🟩🟩🟩

### CODE REVIEW

**Comment by octokatherine** [comment]
to elaborate, I think when people want to share how they did on this game, they can just screenshot the entire game. the purpose of the emoji way of sharing in Wordle is to avoid spoilers about what the word is that day

**Comment by petems** [comment]
Maybe this with the addition of a seed or hash of what the original word was or something?

**Comment by octokatherine** [comment]
as of right now I don't feel that this feature will be useful, and have seen people just sharing screenshots of the game, so I'm going to close out this PR. if people want to discuss this further, feel free to move on over to the dicussions tab of the repo!

**Comment by cmot17** [comment]
@octokatherine not sure if you saw but I opened a discussion here: https://github.com/octokatherine/word-master/discussions/34

**Pull request closed without merging**
