### PR TITLE
toggle endgame UI

### PR DESCRIPTION
**Pull request by teleshoes**
proposed fix for issue #41 / #43, toggle words/endgame

- hamburger button to (re)open endgame
- close button to view words

wm43-1hamburger

wm43-2close

wm43-3init

### CODE REVIEW

**Comment by teleshoes** [comment]
play again could say 'Restart Game' if `gameState !== state.playing`

or when game is over, clicking anywhere except settings/info could re-open endgame instead of having a hamburger

or you could add tabs:
```
/Word Master\  /Results\  /Settings\  /Help\
```
or
```
(%)         /Word Master\  /Results\       (?)
```

**Comment by octokatherine** [comment]
@teleshoes thanks for working on this, it's something people have been asking about a lot! 

Instead of the hamburger icon, could we just have a "play again" button right in that spot when they're in that state? (it wouldn't be the style of the other buttons it would just be text, almost a link style)

which would reset the state and "play again" would disappear on click.

what do you think?

**Comment by teleshoes** [comment]
:)
yea, that's probably better, but then you cant get back to the current/max streak and any future stats that get impl'd.
also, you cant reset the game without refreshing the browser.

anyway, ill see if i can change the hamburger to a play-again some time this week

**Comment by octokatherine** [comment]
> also, you cant reset the game without refreshing the browser
that's what the play again button would do

> then you cant get back to the current/max streak and any future stats that get impl'd
that's true, but that's also the case if you press play again immediately from the modal

**Comment by teleshoes** [comment]
> that's what the play again button would do
oh, i meant resetting it mid-game (if we hide the play-again except when state!=playing). i guess thats not terribly important as you can just refresh or type words.

> that's true, but that's also the case if you press play again immediately from the modal
several times, i would click-out so i can screenshot, then forgot what my streak was and wish i could re-open it and check

**Comment by octokatherine** [comment]
> oh, i meant resetting it mid-game (if we hide the play-again except when state!=playing). i guess thats not terribly important as you can just refresh or type words.

I see what you're saying, we can leave the play again button mid-game, but in that case we have to make sure if they've already guessed a word and then hit play again that we should break their streak (you can't just start over bc its hard and keep your streak. technically you can do that today by refreshing but shh)

**Comment by teleshoes** [comment]
oh dip, i thought it did reset the streak. heh, maybe i should fix that too. (flip a bit in the store when you guess word1, reset it on endgame, and reset the streak in the store if the bit is already flipped when you guess word1)

on further reflection, having the play-again button there to reset is a 1-click kill to someone reaching for the info button..

**Comment by octokatherine** [comment]
> having the play-again button there to reset is a 1-click kill to someone reaching for the info button

that's part of the challenge of the game 😆  jk, yeah that's a fair point. I say drop the button except when state !== playing like you said, and leave refreshing as the only restart option for now. I haven't heard feedback on needing a way to do this from the UI. 

resetting the streak on refresh is definitely a bug, I've known about it for a while and honestly haven't documented it just so people didn't abuse it. plus if you really want to hack your streak you could just change the local storage value. it'd be great to fix though, either here or in a separate pr

**Comment by teleshoes** [comment]
here's my impl of the ui you suggested, lemme know if you want any changes @octokatherine

**Review by octokatherine — APPROVED** [review]
thanks!

**Pull request merged**
