### PR TITLE
enter key restarts game

### PR DESCRIPTION
**Pull request by teleshoes**
just a suggestion. ive been hitting F5, but after persistence, that wont work.

maybe instead of this, just focus the <PlayAgain> button when the modal opens?

also, will rebase this one too. didnt feel like fixing the conflicts twice

### CODE REVIEW

**Comment by teleshoes** [comment]
ah, Keyboard is removed now so this doesnt work. hmm

**Comment by octokatherine** [comment]
hm, not sure I'm understanding the approach you're taking. I think we should be able to just programmatically give focus to the play again button when the modal pops up using a ref

**Comment by teleshoes** [comment]
for sure. this way made a bit more sense when <Keyboard> was always attached. (was nice to separate event/HID logic from game logic)

but yeaaa, if i had known that i wouldnt need to muck about with useRef and adding two different useEffect()s in different files for the two different buttons, i definitely wouldnt have bothered. :)

**Comment by teleshoes** [comment]
@octokatherine this solution appears to Just Work. what do you think?

**Review by octokatherine — APPROVED** [review]
simple, lets try it!

**Pull request merged**
